### ISSUE TITLE
Fixed digit precision

### ISSUE THREAD

**Issue by devgioele** [PgBiel/typst-oxifmt#10]
Is there the possibility of having fixed digit precision?

| input | output |
| --- | --- |
| `20` | `20.00` |
| `1.3` | `1.30` |

**Comment by PgBiel** [comment]
You can use the code below:

```
#import "@preview/oxifmt:0.2.1": strfmt
#strfmt("{:.2} {:.2}", 20.0, 1.3)
```

Though you will need to write `20.0` (i.e. specify a float) rather than `20`. This is consistent with Rust's (our inspiration) behavior, though we could reconsider whether we want to adhere so strictly to that. That could be a separate issue though.

**Comment by devgioele** [comment]
Thank you for the quick reply!
I think sticking to the Rust implementation is a good idea, because it simplifies the package
