### ISSUE TITLE
thousands separator fails

### ISSUE THREAD

**Issue by mgholam** [PgBiel/typst-oxifmt#13]
The following code fails (using oxifmt:0.2.1)
```
#(
	assert.eq(strfmt("{}", 1000, fmt-thousands-separator: "_"), "1_000")
)
```

**Comment by PgBiel** [comment]
You're a bit too fast! This wasn't released yet :)

**Comment by PgBiel** [comment]
You can copy `oxifmt.typ` from the main branch if it's urgent.

**Comment by PgBiel** [comment]
@mgholam if you still need this, oxifmt 1.0.0 is out on the package manager which supports this feature. 👍
