### ISSUE TITLE
Feature request: digit grouping (thousands separator)

### ISSUE THREAD

**Issue by Jollywatt** [PgBiel/typst-oxifmt#5]
I realise that this is supposed to be a port of rust's `format!`, which does not support grouping digits (as in `1,000,000.0000`), but I maybe this feature is commonly wanted in typesetting and can be justified.

(Example use case: At the moment, I'm having to load and combine both `oxifmt` and [`metro`](https://github.com/fenjalien/metro) to format numbers with 1) thousands separators 2) an exact number of decimal digits. If this was added to `oxifmt`, then it alone would be sufficient!)

**Comment by PgBiel** [comment]
Sure, we can do it. Not sure which syntax I would use though, at least without conflicting with the Rust syntax...

Perhaps we could add a second `:` for custom stuff. Or something.
