### ISSUE TITLE
Bug in rendering when using non-ascii in string

### ISSUE THREAD

**Issue by Pluriscient** [PgBiel/typst-oxifmt#6]
When you pass non-ascii character into the format string, it either

**Crashes when passed directly** 
```typst
#import "@preview/oxifmt:0.2.0": strfmt

#strfmt("Hello € {}", "man") // -> Character Boundary at 8
```

**Invalidly renders**
```typst
#import "@preview/oxifmt:0.2.0": strfmt
#let c = yaml("content.yaml")
#strfmt(c.working, company-bank-name: "FAKE", company-bank-iban: "Broken stuff") \
#strfmt(c.broken, company-bank-name: "FAKE", company-bank-iban: "Broken stuff")
```

with `content.yaml`
```yaml
working: "Bank: {company-bank-name} - IBAN: {company-bank-iban}"
broken: "Bank: {company-bank-name} € IBAN: {company-bank-iban}"
```

Rendering
![image](https://github.com/PgBiel/typst-oxifmt/assets/22261839/9b09d8eb-a262-4bf1-832e-fa96841ef5ab)

[Minimal repro's](https://typst.app/project/rp3A1HNoHpG_nj7VDP_oJc)

**Comment by PgBiel** [comment]
Thanks for reporting, this seems bad. I'll take a look.

**Comment by PgBiel** [comment]
Hi, I believe this should be fixed after https://github.com/PgBiel/typst-oxifmt/commit/13f9bedf5573f41c3f9508766044326d27eeb7ac. Can you give it a try in your project and let me know if it's working? Thanks!

**Comment by Pluriscient** [comment]
Hi,

Missed the notifications, apologies. Checked now and [it works](https://typst.app/project/rp3A1HNoHpG_nj7VDP_oJc)!
Thanks for the work :)

**Comment by PgBiel** [comment]
Great, thank you for checking! And you're welcome! 😄
